;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Action.Emote",DevComment="")
+GameplayTagList=(Tag="Ability.Block.Fire",DevComment="")
+GameplayTagList=(Tag="Ability.CoolDown.Banana",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Duration",DevComment="")
+GameplayTagList=(Tag="Event.Bomb.Explode",DevComment="")
+GameplayTagList=(Tag="Event.Gimmick.Collect",DevComment="")
+GameplayTagList=(Tag="Event.Round.Economy.Depression",DevComment="")
+GameplayTagList=(Tag="Event.Round.Economy.Inflation",DevComment="")
+GameplayTagList=(Tag="Event.Weapon.ReloadRefill",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Item.Invisibility",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Explosion",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Fire",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.HitImpact",DevComment="")
+GameplayTagList=(Tag="GameState.MiniGame.Bomb",DevComment="")
+GameplayTagList=(Tag="Input.Action.Crouch",DevComment="")
+GameplayTagList=(Tag="Input.Action.Emote",DevComment="")
+GameplayTagList=(Tag="Input.Action.Equip1",DevComment="")
+GameplayTagList=(Tag="Input.Action.Fire",DevComment="")
+GameplayTagList=(Tag="Input.Action.Interact",DevComment="")
+GameplayTagList=(Tag="Input.Action.Jump",DevComment="")
+GameplayTagList=(Tag="Input.Action.Reload",DevComment="")
+GameplayTagList=(Tag="Input.Action.Sprint",DevComment="")
+GameplayTagList=(Tag="State.HitReaction.HeadShot",DevComment="")
+GameplayTagList=(Tag="State.Idle",DevComment="")
+GameplayTagList=(Tag="State.Movement.InAir",DevComment="")
+GameplayTagList=(Tag="State.Movement.Sprinting",DevComment="")
+GameplayTagList=(Tag="State.Posture.Crouching",DevComment="")
+GameplayTagList=(Tag="State.Status.Bomb",DevComment="")
+GameplayTagList=(Tag="State.Status.Dead",DevComment="")
+GameplayTagList=(Tag="State.Status.Emoting",DevComment="")
+GameplayTagList=(Tag="Weapon.Anim.Fire",DevComment="")
+GameplayTagList=(Tag="Weapon.Anim.Reload",DevComment="")
+GameplayTagList=(Tag="Weapon.Gun.BombPistol",DevComment="")
+GameplayTagList=(Tag="Weapon.Gun.Pistol",DevComment="")
+GameplayTagList=(Tag="Weapon.Gun.Rifle",DevComment="")
+GameplayTagList=(Tag="Weapon.Gun.Rocket",DevComment="")
+GameplayTagList=(Tag="Weapon.State.Equip",DevComment="")
+GameplayTagList=(Tag="Weapon.State.Reload",DevComment="")
+GameplayTagList=(Tag="Weapon.State.UnEquip",DevComment="")

